version: '3.8'

services:
  app:
    build: .
    image: gestor-financeiro:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "3001:3001"
    restart: always
