version: '3.8'

services:
  app:
    build: .
    image: gestor-financeiro:latest
    environment:
      - DB_URL
      - DB_USERNAME
      - DB_PASSWORD
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "3001:3001"
    restart: always
