version: '3.8'

services:
  app:
    build: .
    image: gestor-financeiro:latest
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: always
