# Use root/example as user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: gestor
      POSTGRES_USER: gestor
      POSTGRES_PASSWORD: gestor@admin
    ports:
      - 5432:5432


  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # Porta SMTP
      - "8025:8025" # Porta da interface da web